
const int script_max_count = 53;

const char *script_text[script_max_count] =
{
  "0 Attack target type",
  "1 Attack waypoint",
  "2 Do Nothing",
  "3 Move to waypoint",
  "4 Move to cell",
  "5 Guard area for specified time",
  "6 Jump to script action line",
  "7 Force player win",
  "8 Unload",
  "9 Deploy",
  "10 Follow friendlies",
  "11 Assign new mission",
  "12 Set global variable",
  "13 Play idle anim sequence",
  "14 Load onto transport",
  "15 Spy on structure at waypoint",
  "16 Patrol to waypoint",
  "17 Change script",
  "18 Change team",
  "19 Panic",
  "20 Change house ownership",
  "21 Scatter",
  "22 Afraid and run to shroud",
  "23 Force player loss",
  "24 Play speech",
  "25 Play sound",
  "26 Play movie",
  "27 Play theme",
  "28 Reduce tiberium",
  "29 Begin production",
  "30 Force sale",
  "31 Suicide",
  "32 Start ion storm in",
  "33 End ion storm",
  "34 Center map on team",
  "35 Shroud map for time interval",
  "36 Reveal map for time interval",
  "37 Delete team members",
  "38 Clear global variable",
  "39 Set local variable",
  "40 Clear local variable",
  "41 Unpanic",
  "42 Change facing",
  "43 Wait until fully loaded",
  "44 Unload truck (TRUCKB to TRUCKA)",
  "45 Load truck (TRUCKA to TRUCKB)",
  "46 Attack enemy structure",
  "47 Move to enemy structure",
  "48 Scout",
  "49 Register success",
  "50 Flash",
  "51 Play Animation",
  "52 Display talk bubble"
  };

const char *script_details[script_max_count] =
{
  "Attack the target type and repeat until all of that type are destroyed or the unit runs out of ammo. Selecting target to choose nearest or first created is affected by TargetDistanceCoefficientDefault.",
  "Attack the object if present or the cell at the given waypoint. Action will change accordingly if a structure is present and the team member has attributes of Infiltrate or Engineer or Agent or C4.",
  "Do nothing and proceed to next script action if present. Note: Set parameter to 0 - don't leave it empty.",
  "Orders the team to move to the given waypoint. Action is completed only when all team members reach within a cell distance or equivalent (in case of air).",
  "Orders the team to move to a specific cell on the map within playable boundary. Cell number parameter is X + (Y * 128) in original game. Game computes X as remainder of division by 128 from the cell number. So X value is restricted to below 128. Patch replaces the formula to X + (Y * 1000) so that all coordinates are accessible.",
  "Instructs the team to guard the area for the given units of time. Time units is multiples of 6 seconds (1/10th of a minute). For example 3 means 18 seconds.",
  "Jump to the given line number in the script. Line number starts at 1. It should not be mistaken with the script action index which starts at 0. It is used to create loop in the script.",
  "Forces a game win condition for the owner of the TeamType. Note: Set parameter to 0 - don't leave it empty.",
  "Unloads all loaded units. The parameter specifies which units should stay as part of the team to execute remainder of the script and which should be removed from the team.",
  "Causes all deployable units in the team to deploy. Note: Set parameter to 0 - don't leave it empty.",
  "Causes the team to follow the nearest friendly unit. In AITrigger if the support TeamType has this script action as the first line in its script then the support team will follow the first TeamType. Note: Set parameter to 0 - don't leave it empty.",
  "Team members are assigned with the new mission. In most cases the change remains in effect until the team member is destroyed or recruited into another team. So these actions are kept as last in the script.",
  "Sets the given global variable to true or 1.",
  "If the team contains SHP unit(s) (infantry) then the relevant idle SHP sequence is played as defined by the frame numbering system in art(fs).ini. 0 for Idle1 and 1 for Idle2.",
  "If the TaskForce contains unit(s) having valid Passengers value then this action will make the other units enter the transport. If the task force contains less passengers to load than the transport's capacity then this action remains incomplete. Note: Set parameter to 0 - don't leave it empty.",
  "Instructs the team to enter the structure at the given waypoint and spy on the structure. Use with units having Infiltrate and Agent set.",
  "Move to given waypoint while scanning for enemies within their Sight and actively engage those even if the team has to move out of its patrol route. This action is processor intensive and may cause lag in the game.",
  "Instructs the team to execute another script from [ScriptTypes] table. It uses 0-based list index.",
  "Instructs the TaskForce to join another TeamType listed in the [TeamTypes] table. It uses 0-based list index.",
  "Units having Fraidycat set will run around aimlessly, using the Panic animation from their sequence defined in art(fs).ini. Typically used for the civilian units. Units that do not fulfill this criteria take prone position. Note: Set parameter to 0 - don't leave it empty.",
  "Changes ownership of the TeamType to the specified house index number. Used in single player maps.",
  "Instructs the team members to scatter. Note: Set parameter to 0 - don't leave it empty.",
  "Instructs the team to behave in a scared manner and run to the nearest shrouded cell. The team will not actively engage in combat or acquire targets and will not retaliate (it will scatter instead if attacked). Note: Set parameter to 0 - don't leave it empty.",
  "Forces the owner of the TeamType to lose the game. Note: Set parameter to 0 - don't leave it empty.",
  "Play speech of EVA voices depending on the owner of this team.",
  "Play game sounds from the [SoundList] in the sound(01).ini file using index from its internal table.",
  "Play movie from the [Movies] list in the art(fs).ini file using index from its internal table.",
  "Play music soundtrack from [Themes] list in the theme(01).ini file using index from its internal table.",
  "Reduces the amount of tiberium in the cell that the TeamType is occupying. Note: Set parameter to 0 - don't leave it empty.",
  "Forces the owner of the TeamType to begin the auto-production process. Used on AI controlled houses. Note: Set parameter to 0 - don't leave it empty.",
  "Forces fire sale of all remaining structures owned by the house of the TeamType. Note: Set parameter to 0 - don't leave it empty.",
  "Instructs the team to destroy itself usually accompanied by explosion. Note: Set parameter to 0 - don't leave it empty.",
  "Initiates ion storm after the time specified in seconds.",
  "End the active ion storm. Note: Set parameter to 0 - don't leave it empty.",
  "Center the screen on the team. The parameter gives the speed with which the camera moves. 0 slow to 4 fast.",
  "Shroud the entire map except for the area revealed by the player's own and/or friendly units for the given Duration (number of frames) after which the explored areas are revealed again.",
  "Reveal the entire map for the given Duration (number of frames) after which the map is shrouded again.",
  "Delete team members from the map. Note: Set parameter to 0 - don't leave it empty.",
  "Clears the given global variable or sets it to false or 0.",
  "Sets the given local variable to true or 1.",
  "Clears the given local variable or sets it to false or 0.",
  "If the team contains unit(s) having Fraidycat set which are currently in Panic sequence then this action nullifies that effect and the unit(s) adopt their default behaviour. Note: Set parameter to 0 - don't leave it empty.",
  "Instructs the team to turn and face the new specified direction.",
  "Instructs the transport to wait until fully loaded with passengers before executing any subsequent script actions. It is used after load onto transport action is given. Note: Set parameter to 0 - don't leave it empty.",
  "It converts the unit TRUCKB to TRUCKA which continues any further script actions. It gives the impression of the truck being unloaded. Note: Set parameter to 0 - don't leave it empty.",
  "It converts the unit TRUCKA to TRUCKB which continues any further script actions. It gives the impression of the truck being loaded. Note: Set parameter to 0 - don't leave it empty.",
  "Attack enemy structure specified by the structure number parameter. Structure number is building index + target selection option value. Dropdown shows only the building index + 0 which is set to select the target based on least threat. Use INI editing or text editor to change parameter choices. Add 65536 to building index for highest threat or 131072 for nearest or 196608 for farthest.",
  "Move to enemy structure specified by the structure number parameter. Structure number is building index + target selection option value. Dropdown shows only the building index + 0 which is set to select the target based on least threat. Use INI editing or text editor to change parameter choices. Add 65536 to building index for highest threat or 131072 for nearest or 196608 for farthest.",
  "Move in a random direction. Note: Set parameter to 0 - don't leave it empty.",
  "When the team is formed through AITrigger (not Trigger) then it is flagged for success when this script action is executed by its task force. A script not containing this action is a fail. A script containing this action but the task force being unable to reach and execute this action even once is a fail. This success or failure is used to adjust the current weight defined in its AITrigger. Note: Set parameter to 0 - don't leave it empty.",
  "Flash (visual bright effect) the team for the number of times given in the parameter.",
  "Play animation from [Animations] section list in rules/firestrm.ini file using index from its internal table.",
  "Displays talk bubble above the unit. Parameter 0 for None. 1 for *. 2 for ?. 3 for !."
};

